language: node_js
node_js:
- '10'
deploy:
  provider: gae
  keyfile: api-project.json
  project: dota-2-games-to-google-calendar
  on: master
before_install:
  - openssl aes-256-cbc -K $encrypted_da7f2bf039f1_key -iv $encrypted_da7f2bf039f1_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar